// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using Foundation;
using UIKit;
using TappIOS.Domain.Customer;
using CommonServiceLocator;
using TappIOS.Domain.Customer.VIewModel;

namespace TappIOS.Storyboards
{
    public partial class CustomerRegisteredViewController : UIViewController
    {
        public Customer Customer { get; set; }

        public CustomerRegisteredViewController(IntPtr handle) : base(handle)
        {

        }

        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();

            Debug.Write($"String {Customer.Name}", "DidLoad");

            CreateCustomer();
        }

        private void CreateCustomer()
        {
            var x = ServiceLocator.Current.GetInstance<CustomerViewModel>();
            x.Create(Customer);

            //TODO: check if everything is ok then save
            //TODO: Or show message error
        }

    }
}
