// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using Foundation;
using UIKit;

namespace TappIOS.Storyboards
{
	public partial class CustomerRegisterViewController : UIViewController
	{
		public CustomerRegisterViewController(IntPtr handle) : base(handle)
		{
		}

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();
		}

        partial void btnContinue(Foundation.NSObject sender)
		{
            Debug.Write($"Method name {nameof(ViewDidLoad)}", "Click");

            TattooRegisterViewController tattooRegisterVC = this.Storyboard.InstantiateViewController("TattooRegisterViewController") as TattooRegisterViewController;
            if (tattooRegisterVC != null)
            {
                tattooRegisterVC.Name = "D13";
                this.NavigationController.PushViewController(tattooRegisterVC, true);
            }
        }

        //partial void btnContinueRegisterScreen_TouchUpInside(UIButton sender)
        //{
        //          Debug.Write($"Method name {nameof(ViewDidLoad)}", "Did Load");
        //      }
    }
}
