// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using TappIOS.Domain.User.ViewModel;
using UIKit;
using System.Diagnostics;

namespace TappIOS.Storyboards
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();

            Debug.Write($"Method name {nameof(ViewDidLoad)}", "Did Load");

            //TODO: Set user information from ServiceManager.SetName - SetConfigs - SetCalendar

            //TODO: Show Login Screen. CheckLogin - LoadSegttings - ShowMainMenu

            //TODO: Show main dashboard. 

            //var isLogged = await userViewModel.CheckUserLogin("d13", "d13");

            // Perform any additional setup after loading the view, typically from a nib.
        }
    }
}
