// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TappIOS.Storyboards
{
	public partial class Main2ViewController : UIViewController
	{
		public Main2ViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
