// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TappIOS.Storyboards
{
	public partial class UserCreationViewController : UIViewController
	{
		public UserCreationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
